### ISSUE TITLE
示例博客首页无法加载？

### ISSUE THREAD

**Issue by wenyuanw** [umijs/umi-blog-example#2]
部署在 Vercel 上的示例博客无法正常显示？
Serverless Function 无法正常运行。

![image](https://user-images.githubusercontent.com/49969025/164650043-fa60a8a5-46d6-4458-9af3-fb9855108da7.png)

我自己尝试的时候也是无法成功，不知道是什么原因呢

**Comment by wenyuanw** [comment]
请问`UPSTASH_REDIS_REST_URL `应该怎么设置呢？

**Comment by yuaanlin** [comment]
@wenyuanw 问题解决了吗？

**Comment by wenyuanw** [comment]
> 

本地没什么 dev 运行没有什么大问题，不过现在部署到 vercel 总是失败😭 @ken20001207 
![image](https://user-images.githubusercontent.com/49969025/164707485-6d3b0d96-5444-4a10-80a2-945661ca2602.png)

**Comment by yuaanlin** [comment]
> 本地没什么 dev 运行没有什么大问题，不过现在部署到 vercel 总是失败😭

在 Vercel 看一下 Serverless Function 有没有什么报错日志

**Comment by wenyuanw** [comment]
> > 本地没什么 dev 运行没有什么大问题，不过现在部署到 vercel 总是失败😭
> 
> 在 Vercel 看一下 Serverless Function 有没有什么报错日志

现在是还没能成功部署，环境变量已经设置了

**Comment by yuaanlin** [comment]
@wenyuanw 能发一下你的仓库地址吗？我部署看看哪里出问题了

**Comment by wenyuanw** [comment]
@ken20001207 这个仓库： https://github.com/wenyuanw/umi4-blog-example

**Comment by wenyuanw** [comment]
我基于您的仓库改动并部署之后出现了跟[您现在部署的页面](https://umi-blog-example.vercel.app/)一样的情况，我的[部署](https://umi-blog-wenyuanw.vercel.app/)。

![image](https://user-images.githubusercontent.com/49969025/164724860-0bdb537a-02cc-4b3c-9eeb-7e1ac7f4edd0.png)

**Comment by yuaanlin** [comment]
@wenyuanw 现在的示例博客进不去是因为之前太久没人访问所以数据库服务被暂停了。

你能加一下我钉钉吗？方便排查一下问题。

![IMG_1658](https://user-images.githubusercontent.com/21105863/164726177-c9ff33a8-9f76-4c58-a873-b5d4ee906a00.JPG)

**Comment by yuaanlin** [comment]
@wenyuanw 在 `.npmrc` 文件加入 `node-linker=hoisted` 这一行然后 Vercel 清除缓存重新构建试试
