### ISSUE TITLE
@/utils/jwt 包未找到

### ISSUE THREAD

**Issue by caoLei1997** [umijs/umi-blog-example#3]
大佬好，我想请教下 @/utils/jwt这个是什么安装包，vscode显示找不到模块
我目前是用jwt生成的 token jwt.sign(）

**Comment by yuaanlin** [comment]
@caoLei1997 是源代码中的这个文件 https://github.com/umijs/umi-blog-example/blob/main/utils/jwt.ts

只是配置了绝对路径的别名而已，不是外部的依赖

**Comment by caoLei1997** [comment]
> @caoLei1997 是源代码中的这个文件 https://github.com/umijs/umi-blog-example/blob/main/utils/jwt.ts
> 
> 只是配置了绝对路径的别名而已，不是外部的依赖
