### ISSUE TITLE
新版本加入了REDIS，如何在这项目设置，还有JWT_SECRET

### ISSUE THREAD

**Issue by dong-lufei** [umijs/umi-blog-example#4]
\api\posts\[postId].js:53190       
throw new Error("Unable to find environment variable: `UPSTASH_REDIS_REST_URL`");

**Comment by yuaanlin** [comment]
`UPSTASH_REDIS_REST_URL` 和 `JWT_SECRET` 是环境变量，可以参考文档的 [环境变量](https://umijs.org/docs/guides/env-variables#%E5%A6%82%E4%BD%95%E8%AE%BE%E7%BD%AE%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F) 来查看如何设置。

`UPSTASH_REDIS_REST_URL` 是因为博客用 [Upstash](https://upstash.com/) 提供的 Redis 数据库作为缓存服务，来降低用户打开博客所需要的加载时间。

`JWT_SECRET` 则是用户登入博客时需要用来签发 token 的密钥。

**Comment by MRSHIMMER** [comment]
> `UPSTASH_REDIS_REST_URL` 和 `JWT_SECRET` 是环境变量，可以参考文档的 [环境变量](https://umijs.org/docs/guides/env-variables#%E5%A6%82%E4%BD%95%E8%AE%BE%E7%BD%AE%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F) 来查看如何设置。
> 
> `UPSTASH_REDIS_REST_URL` 是因为博客用 [Upstash](https://upstash.com/) 提供的 Redis 数据库作为缓存服务，来降低用户打开博客所需要的加载时间。
> 
> `JWT_SECRET` 则是用户登入博客时需要用来签发 token 的密钥。

请问怎样生成`JWT_SECRET`？

**Comment by yuaanlin** [comment]
`JWT_SECRET` 可以是任何值，你也可以用 [密码产生器](https://www.lastpass.com/features/password-generator) 生成一个高强度密钥作为 `JWT_SECRET`

**Comment by MRSHIMMER** [comment]
> `JWT_SECRET` 可以是任何值，你也可以用 [密码产生器](https://www.lastpass.com/features/password-generator) 生成一个高强度密钥作为 `JWT_SECRET`

好的，非常感谢。
