### ISSUE TITLE
Error: Unable to find environment variable: `UPSTASH_REDIS_REST_URL`

### ISSUE THREAD

**Issue by ihamlet** [umijs/umi-blog-example#6]
Error: Unable to find environment variable: `UPSTASH_REDIS_REST_URL`

const redis = Redis.fromEnv()

The above code seems to need to configure an environment variable, but I don't know what to use.

**Comment by yuaanlin** [comment]
The current version of example code is using Redis (hosted by [Upstash](https://upstash.com/)) as data caching layer to speed up API route fetching the post data from database.

`UPSTASH_REDIS_REST_URL` is the environment variable for the Redis REST API endpoint. You can follow the instructions on [Upstash Docs](https://docs.upstash.com/redis/howto/connectclient#upstash-redis).
